# Generated by Django 4.2.6 on 2024-01-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
