# Generated by Django 4.2.6 on 2024-01-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_cartdb_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('State', models.CharField(blank=True, max_length=20, null=True)),
                ('Street_Address', models.CharField(blank=True, max_length=10, null=True)),
                ('Town', models.CharField(blank=True, max_length=10, null=True)),
                ('Postcode', models.IntegerField(blank=True, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Email_Address', models.CharField(blank=True, max_length=100, null=True)),
                ('optradio', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
